In [13]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [14]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("World_Weather_Analysis/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Shimoda,JP,2022-12-30 06:54:51,34.6667,138.9500,52.16,58,12,8.14
1,1,Cherskiy,RU,2022-12-30 06:54:52,68.7500,161.3000,-44.63,100,87,3.67
2,2,Tammisaari,FI,2022-12-30 06:54:52,59.9736,23.4339,40.28,99,100,13.91
3,3,Novodugino,RU,2022-12-30 06:54:53,55.6305,34.2842,32.67,99,100,9.26
4,4,Comodoro Rivadavia,AR,2022-12-30 06:54:53,-45.8667,-67.5000,62.46,34,0,13.80

In [15]:
# Get the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [16]:
# CREATE A MAXIMUM TEMPERATURE HEATMAP

# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [17]:
# GENERAL SYNTAX FOR CREATING A HEATMAP

# 1. Assign the locations to an array of latitude and longitude pairs.
    # locations = [latitude, longitude]
# 2. Assign the weights variable to some values.
    # temperatures = #an array of length equal to the locations array length
# 3. Assign the figure variable to the gmaps.figure() attribute.
    # fig = gmaps.figure()
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
    # heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)

# 5. Add the heatmap layer.
    # fig.add_layer(heatmap_layer)
# 6. Call the figure to plot the data.
    # fig

In [18]:
# Heatmap of temperature

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]

# Assign the figure variable.
fig = gmaps.figure()

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# REMOVING NEGATIVE TEMPERATURES
    # Google heatmaps do not plot negative numbers. 
        # If you have a maximum temperature that is less than 0 °F, 
            # then you will get an InvalidWeightException error for this line of code:
                # heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
    # To remove the negative temperatures 
        # we can use a for loop to iterate through the max_temp 
        # and add the temperatures that are greater than 0 °F to a new list.
    # In the for loop, we're using the max() function to get the largest value between the temp and 0. 
        # If the temp is less than 0, then 0 will be added to the list in its place. 
        # Otherwise, the temp is added to the list.
            # Now change the following code in the heat_layer:
                # heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
            # To look like the following:
                # heat_layer = gmaps.heatmap_layer(locations, weights=temps)

In [20]:
# Adjust Heatmap Zoom, Intensity, and Point Radius

# fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# If you review the gmaps documentation, you may notice there is a dissipation option for creating heatmaps that can be added to the gmaps.heat_layer() attribute.
    # The options for this are:
        # The default option for the dissipation is "True," so we need to set our "dissipation" to "False."
        # We can add max_intensity to make each measurement have a better gradient variance.
        # We can add point_radius to make each measurement radius larger.

In [21]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
# GET VACATION CRITERIA
    # For the app we are creating, we need to prompt the user to enter the minimum and maximum temperature ranges as floating-point decimal numbers to filter the city_data_df DataFrame.
        # Recall that you use the input() statement to prompt a user to enter information. 
        # To convert the input to a floating-point decimal number, wrap the input() statement with the float() method, like this: float(input()).

In [25]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [26]:
# filter the maximum temperature column in the city_data_df DataFrame using logical operators to create a new DataFrame with the cities that meet the customer's criteria.
    # Recall that you use the loc[] method on the current DataFrame to create a new DataFrame from a current DataFrame. Inside the brackets, add the conditional filter.
    # The conditional filter will be city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"]>= min_temp.

In [27]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
6,6,Rikitea,PF,2022-12-30 06:54:24,-23.1203,-134.9692,77.56,73,75,4.79
7,7,Avarua,CK,2022-12-30 06:54:55,-21.2078,-159.7750,78.85,83,75,2.30
12,12,Kavaratti,IN,2022-12-30 06:54:57,10.5669,72.6420,82.20,68,83,5.14
31,31,Samarai,PG,2022-12-30 06:55:07,-10.6167,150.6667,82.51,74,100,12.80
32,32,Bengkulu,ID,2022-12-30 06:55:08,-3.8004,102.2655,81.34,77,37,15.17
36,36,Bambous Virieux,MU,2022-12-30 06:55:09,-20.3428,57.7575,82.65,61,20,5.75
45,45,Thinadhoo,MV,2022-12-30 06:56:15,0.5333,72.9333,80.76,76,26,7.92
48,48,Esperance,AU,2022-12-30 06:56:16,-33.8667,121.9000,79.29,51,0,21.16
49,49,Moyale,KE,2022-12-30 06:56:17,3.5167,39.0584,77.16,32,41,21.32
50,50,Balabac,PH,2022-12-30 06:56:18,7.9868,117.0645,81.95,75,99,11.48

In [28]:
preferred_cities_df.count()

City_ID       127
City          127
Country       126
Date          127
Lat           127
Lng           127
Max Temp      127
Humidity      127
Cloudiness    127
Wind Speed    127
dtype: int64

In [29]:
# IMPORTANT
    # Consider the following guidance:
        # Depending on the time of year and the seasons, you might have to adjust the minimum and maximum temperature to get enough cities.
        # It is a good idea to keep the number of cities to fewer than 200 to make it easier to plot the markers on the heatmap.
        # If you have some rows with null values, you'll need to drop them using the dropna() method at the end of your filtering statement when you are creating the new DataFrame.

In [31]:
# GET TRAVEL DESTINATIONS
    # Don't add the hotel information to the preferred_cities_df DataFrame because this DataFrame is our filtered DataFrame, and the customer will always filter it for each trip. 
        # We'll need to create a new DataFrame specifically for the data needed to create a heatmap and pop-up markers.
    # Make a copy of the preferred_cities_df DataFrame and name it hotel_df. 
        # For the hotel_df, keep the columns "City," "Country," "Max Temp," "Lat," and "Lng." 
        # Add a new column to the hotel_df DataFrame to hold the name of the hotel.

In [30]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
6           Rikitea      PF     77.56 -23.1203 -134.9692
7            Avarua      CK     78.85 -21.2078 -159.7750
12        Kavaratti      IN     82.20  10.5669   72.6420
31          Samarai      PG     82.51 -10.6167  150.6667
32         Bengkulu      ID     81.34  -3.8004  102.2655
36  Bambous Virieux      MU     82.65 -20.3428   57.7575
45        Thinadhoo      MV     80.76   0.5333   72.9333
48        Esperance      AU     79.29 -33.8667  121.9000
49           Moyale      KE     77.16   3.5167   39.0584
50          Balabac      PH     81.95   7.9868  117.0645

In [ ]:
# Retrieve Hotels from a Nearby Search

# Set the Parameters for a Nearby Search
    # To find the nearest establishment to geographic coordinates, use the Google Places Nearby Search request. First, navigate to the Nearby Search requests page
    # The Nearby Search request lets us perform these tasks:
        # Search for places within a specified area.
        # Refine the search using keywords and specifying the type of place we are searching for.
        # Use an API URL, where the output can be either XML or JSON format.
    # Although very similar to our OpenWeatherMap API search, with the Google Places Nearby Search, we'll add a specified area and keyword to search.
    # The documentation states we must provide specific parameters.
        # Specific parameters include:
            # Our API key
            # A location, which will be the latitude and longitude
            # A radius for the search. The radius can be up to 50,000 meters or approximately 31 miles. This distance is much too great for finding hotels, so we'll keep our search to 5,000 meters.
            # If we use the rankby=distance for a parameter, we need to add one or more of the three parameters above. We won't use the rankby=distance because we will be searching based on the radius from a given latitude and longitude.
        # We can add optional parameters such as a keyword, a type of business, or the name of a business.

    # For our hotel search, we'll use these parameters:
        # API key
        # Latitude and longitude
        # 5,000-meter radius
        # Type of place
        
# Recall that when we made a request with the OpenWeatherMap API, we added the base URL with the city, city_url, to the request, city_weather = requests.get(city_url).

In [32]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [36]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [37]:
# Recall that when trying to parse the data from an API request, we need to use a try-except block to handle the error with a statement and continue the retrieval.

In [38]:
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
6           Rikitea      PF     77.56 -23.1203 -134.9692
7            Avarua      CK     78.85 -21.2078 -159.7750
12        Kavaratti      IN     82.20  10.5669   72.6420
31          Samarai      PG     82.51 -10.6167  150.6667
32         Bengkulu      ID     81.34  -3.8004  102.2655
36  Bambous Virieux      MU     82.65 -20.3428   57.7575
45        Thinadhoo      MV     80.76   0.5333   72.9333
48        Esperance      AU     79.29 -33.8667  121.9000
49           Moyale      KE     77.16   3.5167   39.0584
50          Balabac      PH     81.95   7.9868  117.0645

In [ ]:
# Create a Maximum Temperature Heatmap from a Hotel DataFrame
    # Before we add pop-up markers with hotel information, 
        # let's create a heatmap using the maximum temperature from our hotel_df DataFrame by reusing the code and changing the DataFrame name.

In [ ]:
# Add a heatmap of temperature for the vacation spots.
    # locations = hotel_df[["Lat", "Lng"]]
    # max_temp = hotel_df["Max Temp"]
    # fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
    # heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
           #  max_intensity=300, point_radius=4)

#fig.add_layer(heat_layer)

# Call the figure to plot the data.
#fig

In [39]:
info_box_template = """

Hotel Name
{Hotel Name}

City
{City}
Country
{Country}
Max Temp
{Max Temp} °F


"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [ ]:
# CODE BREAKDOWN

    # This is a new code block, so let's review its form and function.
        # First, the info_box_template variable is assigned to a multiline string using three quotes. The text inside the multiline string is HTML code. HTML code is defined by the opening and closing the angular brackets (e.g., <tag> and <tag/>). Angular brackets always come in pairs. The opening angular bracket is followed by some text inside, such as dl, dt, and dd. The closing angular bracket is preceded by a forward-slash ("/"). The text inside with the angular brackets is called a tag. We'll see more examples of HTML code in an upcoming module.
        # Here's what these tags mean:
            # The <dl> tag is a description list (dl).
            # The <dt> tag is a term or name in a description list that is nested under the <dl> tag.
            # The <dd> tag is used to define the term or name or <dt> tag.
            # If we were to write out these tags on paper, it would look like this.
                # Description List: <dl>
                # Description Term: <dt>
                # Description Definition: <dd>
                # Description Term: <dt>
                # Description Definition: <dd>
        # For our purposes, we'll add the hotel name, city name, country code, and the maximum temperature values from the hotel_df DataFrame as the description definition
   
    # Next, add the data to the code by iterating through the hotel_df DataFrame using the iterrows() function. Then add the information to the gmaps.marker_layer() attribute with the locations.
        # According to the documentation Links to an external site., we can use this example to create the data for the info_box_template:
        # From the documentation, we can take this code:
            # plant_info = [info_box_template.format(**plant) for plant in nuclear_power_plants]
            # Then edit this code by replacing "plant_info" with "hotel_info," and then use the iterrows() function to get the index and data in the row to add to the marker.
            # Add the following code below to the info_box_template code and run the cell
    
    # DataFrame Row Code Breakdown
        # We set the hotel_info equal to the info_box_content.
        # In the list comprehension, info_box_template.format(**row) for index, row in hotel_df.iterrows(), 
            # we iterate through each "row" of the hotel_df DataFrame and then format the info_box_template with the data we set to populate the from each row. 
            # Remember, we are not using every row; we are only using the rows defined in the info_box_template, which are Hotel Name, City, Country, and Max Temp.

In [41]:
# Heatmap of temperature for vacation spots.
locations = hotel_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = hotel_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, 
                                max_intensity=300, point_radius=3)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Add the maker layer
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))